name: Jalankan WA Checker Bot

on:
  workflow_dispatch: # Biar bisa dinyalain manual pakai tombol

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v3

      - name: Siapkan Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Jalankan Bot
        run: node index.js

